### PR TITLE
Update UMS to 9.4.3

### PR DESCRIPTION
**Pull request by robmonte**

### CODE REVIEW

**Comment by MANICX100** [comment]
Thanks Rob :)

**Comment by robmonte** [comment]
What needs to be done for Chocolatey to detect the update?

**Comment by MANICX100** [comment]
It needed to be pushed to chocolatey.org I have done this. Now all we can do is wait. It is pending review.
Status here: https://chocolatey.org/packages/ums/9.4.3

**Comment by robmonte** [comment]
Okay, awesome! Thanks!

**Comment by MANICX100** [comment]
Approved. I have tweaked the nupkg having the version name in the title broke the file paths when it initially tried to install hence why it was submitted twice. :)

**Pull request merged**
