### PR TITLE
Update iMazing to 3.0.4

### PR DESCRIPTION
**Pull request by alemonmk**
Big thanks to @brogers5 for making this so easy for me to update this package.

### CODE REVIEW

**Comment by brogers5** [comment]
@alemonmk, you may want to get the [Package Triage Process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process/) started if you need an updated package published. @MANICX100 hasn't pushed a commit to this repository for at least 8 months, and I feel it's unlikely he'll push an updated package out if this PR has been sitting for a few months.

**Comment by MANICX100** [comment]
> @alemonmk, you may want to get the [Package Triage Process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process/) started if you need an updated package published. @MANICX100 hasn't pushed a commit to this repository for at least 8 months, and I feel it's unlikely he'll push an updated package out if this PR has been sitting for a few months.

Don't want to ignore you. My main devices have been linux based for a long time and whilst there as copious options I could do with VMs or dualbooting, I dont really want to continue maintaining these packages.

What would be the process to hand off all my packages?

**Comment by brogers5** [comment]
@MANICX100, log in to the Community Repository and follow the Manage Maintainers link on the package page for any package you want to hand off. You can add a new user from there.

I'll volunteer to take over maintenance for `imazing` and `ps-remote-play`. As a reminder, I go by [sublym0nal](https://community.chocolatey.org/profiles/sublym0nal) on the Community Repository.

As for your other packages, I'd recommend raising a [New Maintainer Request](https://github.com/chocolatey-community/chocolatey-package-requests/issues/new?assignees=&labels=&projects=&template=mMaintainerRequest.md) over at the [chocolatey-package-requests repo](https://github.com/chocolatey-community/chocolatey-package-requests) for each.

**Comment by alemonmk** [comment]
> @alemonmk, you may want to get the [Package Triage Process](https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process/) started if you need an updated package published. 

Thanks for attention, I was about to do so but have been procrastinating. If you are taking over `imazing` then I'm closing this PR.

**Comment by brogers5** [comment]
FYI, I haven't been added as a maintainer yet, so the process may still be necessary. I'd say proceed with the Contact Maintainer formality to at least start the clock on it.

**Comment by brogers5** [comment]
Maintainer role has been secured.

@MANICX100, can you clarify the licensing situation for your packages? You currently [do not have a license](https://choosealicense.com/no-permission/) defined, and it'd expedite getting things up and running if I'm able to fork the current state as-is instead of having to recreate the package from scratch.

If you need a suggestion, I typically default to MIT unless the consumed software dictates otherwise.

**Comment by MANICX100** [comment]
Both imazing and PS remote play are proprietary as far as I know.

Dec 11, 2024 5:41:01 PM Brian Rogers ***@***.***>:

**Comment by brogers5** [comment]
I was referring to the package's code, not the underlying software...

**Comment by MANICX100** [comment]
I accept MIT and want no restrictions on the package files themselves

Dec 11, 2024 5:50:44 PM Brian Rogers ***@***.***>:

**Comment by alemonmk** [comment]
@brogers5 I found your new repo so I'm closing this, thanks.

**Comment by brogers5** [comment]
v3.0.6 has been pushed, and should be available once the moderation process completes:
https://community.chocolatey.org/packages/imazing/3.0.6

Since the package is still trusted (likely because we went outside of the usual RFM workflow), it likely will only take a couple of hours or so before it's live for consumption.

**Pull request closed without merging**
